### ISSUE TITLE
Can you add more roles like the other roles?

### ISSUE THREAD

**Issue by ponyzerteal** [MyDragonBreath/MDB-TownOfUs-Branch-Releases#1]
I downloaded your revision and played in my discussion group. I hope you can update some more interesting roles and modifiers.

**Comment by MyDragonBreath** [comment]
Hey - I've recently joined the TOU-R team and have been hard at work bringing submerged compatibility and QOL. While some of my more outlandish ideas will remain (and continue to be built) here, the majority of my work will go to the official fork. While I can't say much, both `assassinating crewmate modifiers` and `horse mode` will make a much more stable and "vanilla" appearance in v3.1.0. I do hope you understand.

**Comment by ponyzerteal** [comment]
Wow, I look forward to your surprise.
